name: Publish PyPI Redirects

"on":
    workflow_dispatch: ~

jobs:
    typed_classproperty-redirect:
        environment: redirect-publish-typed_classproperty
        permissions:
            id-token: write
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
              with:
                fetch-depth: 0

            - name: Install uv
              uses: astral-sh/setup-uv@v6

            - name: Build Package
              run: uv build --sdist
              working-directory: ./.pypi-redirects/typed_classproperty

            - name: Publish to PyPI
              run: uv publish
              working-directory: ./.pypi-redirects/typed_classproperty
